import "./globals.css";
import { Inconsolata } from "next/font/google";
import Navbar from './components/Navbar'

const inconsolata = Inconsolata({ subsets: ["latin"]});

export const metadata = {
  title: "Trippy",
  description: "Generated by create next app",
};

import { Providers } from "./providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inconsolata.className}>
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
